version: '3'

services:
 db:
  image: postgres
  restart: always
  environment:
   POSTGRES_PASSWORD: password123
  volumes:
    - ../../database/postgres_data:/var/lib/postgresql/data
  ports:
    - 5432:5432
volumes:
  postgres_data:
